# Generated by Django 4.2.2 on 2023-06-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_num",
        ),
    ]
