# Generated by Django 4.2.2 on 2023-06-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0002_remove_question_question_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="questin_text",
            new_name="question_text",
        ),
    ]
