# Generated by Django 4.2.2 on 2023-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizapp", "0003_rename_questin_text_question_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
